spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:9000
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/api/v1/(?<segment>.*),/api/v1/$\<segment>
          - id: category-service
            uri: http://localhost:9002
            predicates:
              - Path=/categories/**
            filters:
              - RewritePath=/api/v1/(?<segment>.*),/api/v1/$\<segment>
          - id: media-service
            uri: http://localhost:2120
            predicates:
              - Path=/v1/files/**
            filters:
              - RewritePath=/api/v1/(?<segment>.*),/api/v1/$\<segment>
          - id: event-service
            uri: http://localhost:9001
            predicates:
              - Path=/events/**
            filters:
              - RewritePath=/api/v1/(?<segment>.*),/api/v1/$\<segment>
server:
  port: 7894