spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:9000
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/api/v1/(?<segment>.*),/api/v1/$\<segment>
server:
  port: 7894