server:
  port: ${PORT:2120}

spring:
  application:
    name: media-service
  profiles:
    active:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:6969/coredb?currentSchema=media-service}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: media-service
#  cloud:
#    azure:
#      storage:
#        blob:
#          accountName: ${AZURE_BLOB_NAME}
#          accountKey: ${AZURE_BLOB_KEY}
#          endpoint: ${AZURE_BLOB_ENDPOINT}
#          containerName: ${AZURE_BLOB_CONTAINER_NAME}
cloud:
  blob:
    sas:
      accessDuration: 900
scheduling:
  file:
    operation:
      delete:
        time: 30
        #Every midnight
        interval: 0 0 0 * * *
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka

