server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG

spring:
  application:
    name: discovery-service
