spring:
  profiles:
    active:
  application:
    name: website-core
  datasource:
    url: jdbc:postgresql://localhost:6969/coredb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  springdoc:
    version : 2.5.0
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html






      #base-path: /user-service #/users
#    show-actuator: true
 #   management:
  #    endpoints:
   #     web:
    #      exposure:
     #       include: swagger-ui
      #server:
       # port: 8080

    #    springdoc:
 #    swagger-ui:
  #     operationsSorter: method
   #  api-docs:
    #   path: /api-docs
